const bios = [
  {
    id: 1,
    name: 'Onyeabo Okafor',
    position: 'CHAIRMAN LP&CO.',
    fullPosition: 'Chairman LP&CO., NIGERIA, ZAMBIA.',
    imageUrl: 'https://res.cloudinary.com/https-www-lawrencepriceltd-com/image/upload/v1619184026/blackboxlanding/okafor_iwsoeo.svg',
    linkedIn: 'ss',
    paragraph1: 'That is just what I was about to venture to propose,” returned the doctor with a smile. But the words were hardly uttered, before the smile was struck out of his face and succeeded by an expression of such abject terror and despair, as froze the very blood of the two gentlemen below.',
    paragraph2: 'They saw it but for a glimpse for the window was instantly thrust down; but that glimpse had been sufficient, and they turned and left the court without a word.In silence, too, they traversed the by- street; and it was not until they had come into a neighbouring thoroughfare, where even upon a Sunday there were still some stirrings of life, that Mr.',
    paragraph3: ' Utterson at last turned and looked at his companion.They were both pale; and there was an answering horror in their eyes.',
    quote: 'Passion Begets Mastery.',
  },
  {
    id: 2,
    name: 'Oluseun Taiwo',
    position: 'GCEO  LP&CO, NIGERIA, ZAMBIA.',
    fullPosition: 'Group Chief Executive Officer LP&CO., NIGERIA,ZAMBIA.',
    imageUrl: 'https://res.cloudinary.com/https-www-lawrencepriceltd-com/image/upload/v1619184001/blackboxlanding/sean_sibgwd.svg',
    linkedIn: 'https://www.linkedin.com/in/oluseun-t-abb95893/',
    paragraph1: 'That is just what I was about to venture to propose,” returned the doctor with a smile. But the words were hardly uttered, before the smile was struck out of his face and succeeded by an expression of such abject terror and despair, as froze the very blood of the two gentlemen below.',
    paragraph2: 'They saw it but for a glimpse for the window was instantly thrust down; but that glimpse had been sufficient, and they turned and left the court without a word.In silence, too, they traversed the by- street; and it was not until they had come into a neighbouring thoroughfare, where even upon a Sunday there were still some stirrings of life, that Mr.',
    paragraph3: ' Utterson at last turned and looked at his companion.They were both pale; and there was an answering horror in their eyes.',
    quote: 'Passion Begets Mastery.',
  },
  {
    id: 3,
    name: 'Abiodun A.',
    position: 'MD, Business Solutions  LP&CO.',
    fullPosition: 'Managing Director, Business Solutions LP&CO.',
    imageUrl: 'https://res.cloudinary.com/https-www-lawrencepriceltd-com/image/upload/v1618821392/blackboxlanding/IMG_3017_ltypby.jpg',
    linkedIn: 'https://www.linkedin.com/in/adejumo-abiodun-0143a275/',
    paragraph1: 'That is just what I was about to venture to propose,” returned the doctor with a smile. But the words were hardly uttered, before the smile was struck out of his face and succeeded by an expression of such abject terror and despair, as froze the very blood of the two gentlemen below.',
    paragraph2: 'They saw it but for a glimpse for the window was instantly thrust down; but that glimpse had been sufficient, and they turned and left the court without a word.In silence, too, they traversed the by- street; and it was not until they had come into a neighbouring thoroughfare, where even upon a Sunday there were still some stirrings of life, that Mr.',
    paragraph3: ' Utterson at last turned and looked at his companion.They were both pale; and there was an answering horror in their eyes.',
    quote: 'Passion Begets Mastery.',
  },
  {
    id: 4,
    name: 'Rukayat Olawuyi',
    position: 'HEAD DATA & ANALYTICS  LP&CO.',
    fullPosition: 'Head Data And Analytics LP&CO.',
    imageUrl: 'https://res.cloudinary.com/https-www-lawrencepriceltd-com/image/upload/v1618305827/blackboxlanding/Rukayat_1.25x_zlw96o.jpg',
    linkedIn: 'https://www.linkedin.com/in/rukayat-olawuyi-78213947/',
    paragraph1: 'That is just what I was about to venture to propose,” returned the doctor with a smile. But the words were hardly uttered, before the smile was struck out of his face and succeeded by an expression of such abject terror and despair, as froze the very blood of the two gentlemen below.',
    paragraph2: 'They saw it but for a glimpse for the window was instantly thrust down; but that glimpse had been sufficient, and they turned and left the court without a word.In silence, too, they traversed the by- street; and it was not until they had come into a neighbouring thoroughfare, where even upon a Sunday there were still some stirrings of life, that Mr.',
    paragraph3: ' Utterson at last turned and looked at his companion.They were both pale; and there was an answering horror in their eyes.',
    quote: 'Passion Begets Mastery.',
  },
  {
    id: 5,
    name: 'Olamide Balogun',
    position: 'Head Human resources',
    fullPosition: 'Head of Human Resources LP&CO.',
    imageUrl: 'https://res.cloudinary.com/https-www-lawrencepriceltd-com/image/upload/v1618305565/blackboxlanding/Olamide-_Head_Humsn_Resource._1.25x_hhrk5m.jpg',
    linkedIn: 'https://www.linkedin.com/in/olamide-balogun-60b78a166/',
    paragraph1: 'That is just what I was about to venture to propose,” returned the doctor with a smile. But the words were hardly uttered, before the smile was struck out of his face and succeeded by an expression of such abject terror and despair, as froze the very blood of the two gentlemen below.',
    paragraph2: 'They saw it but for a glimpse for the window was instantly thrust down; but that glimpse had been sufficient, and they turned and left the court without a word.In silence, too, they traversed the by- street; and it was not until they had come into a neighbouring thoroughfare, where even upon a Sunday there were still some stirrings of life, that Mr.',
    paragraph3: ' Utterson at last turned and looked at his companion.They were both pale; and there was an answering horror in their eyes.',
    quote: 'Passion Begets Mastery.',
  },
  {
    id: 6,
    name: 'Rafiat Bashorun',
    position: 'Head of finance lp&co.',
    fullPosition: 'Head of Finanace, LP&CO',
    imageUrl: 'https://res.cloudinary.com/https-www-lawrencepriceltd-com/image/upload/v1618305491/blackboxlanding/MicrosoftTeams-image_2_x7idrt.jpg',
    linkedIn: 'https://www.linkedin.com/in/rafiat-bashorun-aca/',
    paragraph1: 'That is just what I was about to venture to propose,” returned the doctor with a smile. But the words were hardly uttered, before the smile was struck out of his face and succeeded by an expression of such abject terror and despair, as froze the very blood of the two gentlemen below.',
    paragraph2: 'They saw it but for a glimpse for the window was instantly thrust down; but that glimpse had been sufficient, and they turned and left the court without a word.In silence, too, they traversed the by- street; and it was not until they had come into a neighbouring thoroughfare, where even upon a Sunday there were still some stirrings of life, that Mr.',
    paragraph3: ' Utterson at last turned and looked at his companion.They were both pale; and there was an answering horror in their eyes.',
    quote: 'Passion Begets Mastery.',
  },
  {
    id: 7,
    name: 'Omosuyi O.',
    position: 'coo.  lp& Co',
    fullPosition: 'Chief Operating Officer, LP&CO',
    imageUrl: 'https://res.cloudinary.com/https-www-lawrencepriceltd-com/image/upload/v1618305707/blackboxlanding/Omosuyi_kwbvq7.jpg',
    linkedIn: 'https://www.linkedin.com/in/omosuyi-oluwafemi/',
    paragraph1: 'That is just what I was about to venture to propose,” returned the doctor with a smile. But the words were hardly uttered, before the smile was struck out of his face and succeeded by an expression of such abject terror and despair, as froze the very blood of the two gentlemen below.',
    paragraph2: 'They saw it but for a glimpse for the window was instantly thrust down; but that glimpse had been sufficient, and they turned and left the court without a word.In silence, too, they traversed the by- street; and it was not until they had come into a neighbouring thoroughfare, where even upon a Sunday there were still some stirrings of life, that Mr.',
    paragraph3: 'Utterson at last turned and looked at his companion.They were both pale; and there was an answering horror in their eyes.',
    quote: 'Passion Begets Mastery.',
  },
  {
    id: 8,
    name: 'Michael M',
    position: 'Head of software lp&co.',
    fullPosition: 'Head of Software Engineering, LP&CO',
    imageUrl: 'https://res.cloudinary.com/https-www-lawrencepriceltd-com/image/upload/v1618305400/blackboxlanding/IMG_0491_wrwjfz.jpg',
    linkedIn: 'https://www.linkedin.com/in/michael-mekuleyi-22ab41149/',
    paragraph1: 'That is just what I was about to venture to propose,” returned the doctor with a smile. But the words were hardly uttered, before the smile was struck out of his face and succeeded by an expression of such abject terror and despair, as froze the very blood of the two gentlemen below.',
    paragraph2: 'They saw it but for a glimpse for the window was instantly thrust down; but that glimpse had been sufficient, and they turned and left the court without a word.In silence, too, they traversed the by- street; and it was not until they had come into a neighbouring thoroughfare, where even upon a Sunday there were still some stirrings of life, that Mr.',
    paragraph3: ' Utterson at last turned and looked at his companion.They were both pale; and there was an answering horror in their eyes.',
    quote: 'Passion Begets Mastery.',
  },
];

export default bios;
